FROM node:latest
MAINTAINER Elegancetse

# Add some file to container
COPY . /togetherjs
WORKDIR /togetherjs
RUN npm install
RUN npm install -g grunt-cli

# build and run server
RUN grunt build buildsite --no-hardlink

EXPOSE 8090 8091
CMD ["node","hub/server.js"]
